(function(root){
  'use strict';
  var DIN=root.DIN4,$=function(id){return document.getElementById(id);},snapshot=null,model=null,mode='groups',busy=false,currentPlan=null,currentRoomId='',mapScale=1,basePlans=Array.isArray(root.DIN_PLANOS)?root.DIN_PLANOS.slice():[];
  function empty(title,detail){return '<div class="empty"><strong>'+DIN.esc(title)+'</strong><span>'+DIN.esc(detail||'')+'</span></div>';}
  function mergePlans(dynamic){dynamic=Array.isArray(dynamic)?dynamic:[];return basePlans.filter(function(p){return !dynamic.some(function(q){return q.id===p.id||(q.edificio===p.edificio&&DIN.norm(q.planta)===DIN.norm(p.planta));});}).concat(dynamic);}
  function periodId(){return model&&model.period?model.period.id_periodo:'';}
  function refreshStats(){
    $('statGroups').textContent=model.groups.length;
    $('statTutors').textContent=new Set(model.groups.filter(function(g){return DIN.hasTutor(g.tutor);}).map(function(g){return DIN.norm(g.tutor);})).size;
    $('statBuildings').textContent=model.buildings.length;
    $('statPlans').textContent=model.plans.filter(function(p){return model.buildings.some(function(b){return b.id_edificio===p.edificio;});}).length;
    $('statTeachers').textContent=root.DIN_SCHEDULE4?root.DIN_SCHEDULE4.count('profesores'):0;
  }
  function refreshCareer(){var old=$('career').value,names=Array.from(new Set(model.groups.map(function(g){return DIN.str(g.ingenieria);}).filter(Boolean))).sort(DIN.natural);$('career').innerHTML='<option value="">Todas las carreras</option>'+names.map(function(x){return '<option value="'+DIN.esc(x)+'">'+DIN.esc(x)+'</option>';}).join('');if(names.indexOf(old)>=0)$('career').value=old;}
  async function start(force){
    if(busy)return;busy=true;$('refresh').disabled=true;$('period').disabled=true;$('connection').textContent='Conectando…';$('status').className='status';$('status').textContent='Actualizando información…';
    try{
      var result=await root.DIN_SOURCE4.load(!!force);snapshot=result.snapshot;root.DIN_PLANOS=mergePlans(snapshot.plans||[]);model=DIN.model(Object.assign({},snapshot,{plans:root.DIN_PLANOS}),snapshot.active);root.DIN_SCHEDULE4.setSnapshot(snapshot);root.DIN_CAMPUS4.setContext(snapshot,model);
      var ps=model.periods;$('period').innerHTML=ps.length?ps.map(function(p){return '<option value="'+DIN.esc(p.id_periodo)+'">'+DIN.esc(p.nombre)+'</option>';}).join(''):'<option>Sin periodo vigente</option>';$('period').disabled=ps.length<2;if(model.period)$('period').value=model.period.id_periodo;
      $('periodBadge').textContent='Vigente';$('connection').textContent=result.stale?'Copia confirmada':'Datos actualizados';var d=new Date(snapshot.updated||'');$('dataUpdated').textContent=isFinite(d.getTime())?'Actualización: '+d.toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'}):'';
      refreshCareer();refreshStats();$('status').textContent=result.warning||'';render();
    }catch(e){$('connection').textContent='Sin conexión';$('status').className='status error';$('status').textContent=(e&&e.message||'No se pudo cargar la consulta.')+' Intenta de nuevo.';$('results').innerHTML=empty('Información no disponible','La página no mostrará ubicaciones sin confirmar.');}
    finally{busy=false;$('refresh').disabled=false;}
  }
  function matchingGroups(q){q=DIN.norm(q);var career=$('career').value;return model.groups.filter(function(g){if(career&&g.ingenieria!==career)return false;var text=DIN.norm([g.grupo,g.tutor,g.correo,g.ingenieria,g.salida_lateral,g.generacion].join(' '));return q.split(' ').filter(Boolean).every(function(t){return text.indexOf(t)>=0;});});}
  function groupTile(g){return '<strong>'+DIN.esc(g.grupo)+'</strong><small>'+DIN.esc(g.ingenieria||'Carrera pendiente')+'</small>'+(g.cuatrimestre?'<small>'+DIN.esc(g.cuatrimestre)+'º cuatrimestre</small>':'')+(DIN.hasTutor(g.tutor)?'<small>Tutor: '+DIN.esc(g.tutor)+'</small>':'');}
  function groupCard(g){var placements=model.placements(g),email=DIN.str(g.correo),mail=/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(email);return '<article class="group-card"><h3 class="code">'+DIN.esc(g.grupo)+'</h3><p>'+DIN.esc(g.ingenieria||'')+(g.salida_lateral?' · '+DIN.esc(g.salida_lateral):'')+'</p>'+(DIN.hasTutor(g.tutor)?'<div class="field"><small>TUTOR / TUTORA</small><strong>'+DIN.esc(g.tutor)+'</strong></div>':'')+'<div class="fields"><div class="field"><small>GENERACIÓN</small>'+DIN.esc(g.generacion||'—')+'</div><div class="field"><small>CORREO</small>'+(mail?'<a href="mailto:'+DIN.esc(email)+'">'+DIN.esc(email)+'</a>':'Pendiente')+'</div></div>'+(placements.length?placements.map(function(p){return '<div class="placement"><strong>'+DIN.esc(model.buildingLabel(p.building))+'</strong><p>Planta '+DIN.esc(p.room.planta)+' · '+DIN.esc(model.roomLabel(p.room))+' · '+DIN.esc(p.assignment.turno||'Turno no indicado')+'</p><button type="button" class="map-button" data-room="'+DIN.esc(p.room.id_aula)+'">Ubicar mi aula ↗</button></div>';}).join(''):'<p class="schedule-notice">Aula pendiente de asignación para este periodo.</p>')+'</article>';}
  function locationGuide(g){var ps=model.placements(g);return '<section class="group-card"><h3>'+DIN.esc(g.grupo)+' · Localiza tu salón</h3>'+(ps.length?ps.map(function(p){return '<article><ol class="location-steps"><li><small>1 · Edificio</small><strong>'+DIN.esc(model.buildingLabel(p.building))+'</strong></li><li><small>2 · Planta</small><strong>'+DIN.esc(p.room.planta)+'</strong></li><li><small>3 · Aula</small><strong>'+DIN.esc(model.roomLabel(p.room))+'</strong></li></ol><button class="map-button" data-room="'+DIN.esc(p.room.id_aula)+'">Abrir croquis ↗</button></article>';}).join(''):'<p>Aula pendiente de asignación.</p>')+'</section>';}
  function renderGroups(q){var gs=matchingGroups(q);$('resultTitle').textContent=mode==='locate'?'Localiza tu salón':'Grupos del periodo';$('count').textContent=gs.length+' grupos';$('results').innerHTML=gs.length?'<div class="group-picker">'+gs.map(function(g){return '<button class="group-pick" type="button" data-group="'+DIN.esc(g.id_grupo)+'">'+groupTile(g)+'</button>';}).join('')+'</div><div id="groupDetail"></div>':empty('Sin coincidencias','Prueba otro código, tutor o carrera.');}
  function renderTutors(q){var gs=matchingGroups(q),map=new Map();gs.forEach(function(g){if(DIN.hasTutor(g.tutor)){var k=DIN.norm(g.tutor);if(!map.has(k))map.set(k,[]);map.get(k).push(g);}});var entries=Array.from(map.values()).sort(function(a,b){return DIN.natural(a[0].tutor,b[0].tutor);});$('resultTitle').textContent='Tutores y sus grupos';$('count').textContent=entries.length+' tutores';$('results').innerHTML=entries.length?entries.map(function(arr){var e=arr[0].correo;return '<details class="tutor-card"><summary><strong>'+DIN.esc(arr[0].tutor)+'</strong><span>'+arr.length+' grupo(s)</span></summary><p>'+(/^[^\s@<>]+@/.test(e||'')?'<a href="mailto:'+DIN.esc(e)+'">'+DIN.esc(e)+'</a>':'Correo pendiente')+'</p><p>'+arr.map(function(g){return '<button type="button" class="schedule-chip" data-group="'+DIN.esc(g.id_grupo)+'">'+DIN.esc(g.grupo)+'</button>';}).join(' ')+'</p></details>';}).join(''):empty('Sin tutores','No hay coincidencias.');}
  function render(){if(!model)return;var q=$('search').value;$('clear').hidden=!q;if(['profesores','grupos','salones'].indexOf(mode)>=0){$('academicSearch').hidden=true;$('academicHeading').hidden=true;$('results').hidden=true;$('horarios').hidden=false;root.DIN_SCHEDULE4.mount(mode,$('horarios'));return;}$('academicSearch').hidden=false;$('academicHeading').hidden=false;$('results').hidden=false;$('horarios').hidden=true;if(mode==='tutors')renderTutors(q);else renderGroups(q);}
  function openRoom(roomId){var r=model.roomById(roomId);if(!r)return;var geo=model.geometry(r);if(!geo){alert('El aula está registrada, pero su croquis todavía no está publicado.');return;}currentPlan=geo.plan;currentRoomId=r.id_aula;mapScale=1;openPlan();}
  function openMapForBuilding(buildingId,floor){var p=model.plans.find(function(x){return x.edificio===buildingId&&(!floor||DIN.norm(x.planta)===DIN.norm(floor));});if(!p){alert('Croquis pendiente de publicar para esta planta.');return;}currentPlan=p;currentRoomId='';mapScale=1;openPlan();}
  function openPlan(){if(!currentPlan)return;$('mapTitle').textContent=(model.buildings.find(function(b){return b.id_edificio===currentPlan.edificio;})?model.buildingLabel(model.buildings.find(function(b){return b.id_edificio===currentPlan.edificio;})):currentPlan.edificio);var same=model.plans.filter(function(p){return p.edificio===currentPlan.edificio;});$('floor').innerHTML=same.map(function(p){return '<option value="'+DIN.esc(p.id)+'">'+DIN.esc(p.planta)+'</option>';}).join('');$('floor').value=currentPlan.id;$('mapSubtitle').textContent='Toca un aula para consultar su asignación vigente.';drawPlan();$('mapDialog').showModal();}
  function drawPlan(){if(!currentPlan)return;var w=Number(currentPlan.width||900),h=Number(currentPlan.height||400),spaces=currentPlan.spaces||[],svg='<svg viewBox="0 0 '+w+' '+h+'" xmlns="http://www.w3.org/2000/svg">';if(currentPlan.background)svg+='<image href="'+DIN.esc(currentPlan.background)+'" width="'+w+'" height="'+h+'" preserveAspectRatio="none"/>';spaces.forEach(function(s){var selected=currentRoomId&&(String(s.roomId)===String(currentRoomId));var fill=selected?'#f7d552':(s.kind==='room'?'#dcefe8':'#e8edf0'),stroke=selected?'#8b6c00':'#7995a2';if(Array.isArray(s.points)&&s.points.length>=3)svg+='<polygon data-space="'+DIN.esc(s.key)+'" points="'+s.points.map(function(p){return p[0]+','+p[1];}).join(' ')+'" fill="'+fill+'" stroke="'+stroke+'" stroke-width="2"/>';else svg+='<rect data-space="'+DIN.esc(s.key)+'" x="'+Number(s.x||0)+'" y="'+Number(s.y||0)+'" width="'+Number(s.w||1)+'" height="'+Number(s.h||1)+'" rx="4" fill="'+fill+'" stroke="'+stroke+'" stroke-width="2"/>';var x=Number(s.x||0)+Number(s.w||1)/2,y=Number(s.y||0)+Number(s.h||1)/2;svg+='<text x="'+x+'" y="'+y+'" text-anchor="middle" dominant-baseline="middle" font-size="11" fill="#26485b">'+DIN.esc(s.label||s.key)+'</text>';});svg+='</svg>';$('mapCanvas').innerHTML=svg;$('mapCanvas').style.width=(mapScale*100)+'%';var rooms=model.rooms.filter(function(r){var g=model.geometry(r);return g&&g.plan.id===currentPlan.id;});$('roomButtons').innerHTML=rooms.map(function(r){return '<button type="button" class="schedule-chip" data-room="'+DIN.esc(r.id_aula)+'">'+DIN.esc(model.roomLabel(r))+'</button>';}).join('');var chosen=currentRoomId&&model.roomById(currentRoomId);if(chosen){var gs=model.groups.filter(function(g){return model.placements(g).some(function(p){return p.room.id_aula===chosen.id_aula;});});$('roomDetail').innerHTML='<strong>'+DIN.esc(model.roomLabel(chosen))+'</strong><p>'+DIN.esc(gs.map(function(g){return g.grupo;}).join(', ')||'Sin grupo asignado')+'</p>';}else $('roomDetail').innerHTML='';}
  function selectMode(next){mode=next;Array.prototype.forEach.call(document.querySelectorAll('[data-mode]'),function(b){var on=b.getAttribute('data-mode')===mode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on?'true':'false');});$('hint').textContent=['profesores','grupos','salones'].indexOf(mode)>=0?'Selecciona o busca el horario que necesitas. Solo se carga el resultado elegido.':mode==='locate'?'Elige tu grupo para ver edificio, planta y aula.':'Busca por grupo, tutor, carrera o correo.';render();}
  document.addEventListener('DOMContentLoaded',function(){
    $('refresh').onclick=function(){start(true);};$('search').oninput=render;$('career').onchange=render;$('clear').onclick=function(){$('search').value='';render();};$('period').onchange=function(){model=DIN.model(Object.assign({},snapshot,{plans:root.DIN_PLANOS}),$('period').value);root.DIN_CAMPUS4.setContext(snapshot,model);refreshCareer();refreshStats();render();};
    document.querySelector('.tabs').onclick=function(e){var b=e.target.closest('[data-mode]');if(b)selectMode(b.getAttribute('data-mode'));};
    $('results').onclick=function(e){var g=e.target.closest('[data-group]'),r=e.target.closest('[data-room]');if(r)openRoom(r.getAttribute('data-room'));else if(g){var group=model.groupById(g.getAttribute('data-group'));var detail=$('groupDetail');if(!detail){detail=document.createElement('div');detail.id='groupDetail';$('results').appendChild(detail);}detail.innerHTML=mode==='locate'?locationGuide(group):groupCard(group);detail.scrollIntoView({behavior:'smooth',block:'nearest'});}};
    $('mapDialog').onclick=function(e){var r=e.target.closest('[data-room]');if(r){currentRoomId=r.getAttribute('data-room');drawPlan();}};$('closeMap').onclick=function(){$('mapDialog').close();};$('floor').onchange=function(){currentPlan=model.plans.find(function(p){return p.id===$('floor').value;});currentRoomId='';drawPlan();};$('zoomIn').onclick=function(){mapScale=Math.min(3,mapScale+.5);drawPlan();};$('zoomOut').onclick=function(){mapScale=Math.max(1,mapScale-.5);drawPlan();};$('zoomReset').onclick=function(){mapScale=1;drawPlan();};
    start(false);
  });
  root.DIN_APP4={periodId:periodId,openMapForBuilding:openMapForBuilding,openRoom:openRoom};
})(window);
