(function(root){'use strict';
var DIN=root.DIN,snapshot=null,model=null,selected=-1,scale=1;
// Referencia del mapa físico indicada por administración: D = 7EE y E = 4EE.
// Esta capa pública solo resalta los edificios DIN activos; esas referencias no se dibujan como edificios DIN.
var baseline=[
{id:'NANO_H1',name:'Nano',aliases:['N','NANO (H1)','NANO_H1','H1','NANO'],points:'645,896 763,845 791,905 672,959',label:{x:718,y:818,text:'NANO'}},
{id:'AMBIENTAL_H',name:'H · Ambiental',aliases:['AMBIENTAL (H)','AMBIENTAL_H','H'],points:'714,995 847,940 875,1004 742,1060',label:{x:795,y:914,text:'H · Ambiental'}},
{id:'I',name:'I',aliases:['I'],points:'768,1137 906,1078 930,1134 791,1194',label:{x:850,y:1050,text:'I'}},
{id:'F',name:'F',aliases:['F'],points:'958,1270 1092,1217 1119,1277 989,1336',label:{x:1042,y:1190,text:'F'}},
{id:'G',name:'G',aliases:['G'],points:'955,922 1088,866 1115,932 980,987',label:{x:1037,y:838,text:'G'}},
{id:'CIC',name:'CIC 4.0',aliases:['CIC','CIC 4.0'],points:'920,414 948,369 934,340 1034,298 1065,256 1106,269 1076,318 1090,345 1000,380 956,431',label:{x:1015,y:230,text:'CIC 4.0'}},
{id:'PIDET',name:'PIDET',aliases:['PIDET'],points:'901,242 932,194 916,168 1025,123 1048,85 1090,96 1070,139 1090,172 984,215 939,260',label:{x:998,y:60,text:'PIDET'}}
];
function $(id){return document.getElementById(id);}function buildingFor(a){if(!model)return null;return model.buildings.find(function(b){return DIN.norm(b.id_edificio)===DIN.norm(a.id);})||model.buildings.find(function(b){return (a.aliases||[]).some(function(x){return [b.id_edificio,b.nombre,b.nombre_completo].some(function(v){return DIN.norm(v)===DIN.norm(x);});});});}
function areas(){var dynamic=(snapshot&&snapshot.campusAreas||[]).filter(function(a){return a&&a.id_edificio&&a.points;}).map(function(a){var b=model&&model.buildings.find(function(x){return String(x.id_edificio)===String(a.id_edificio);});return {id:a.id_edificio,name:b?model.buildingLabel(b):(a.name||a.id_edificio),aliases:[a.id_edificio],points:a.points,label:a.label||null};});var known=baseline.slice();dynamic.forEach(function(d){var db=buildingFor(d),exists=known.some(function(b){var bb=buildingFor(b);return db&&bb&&db.id_edificio===bb.id_edificio;});if(!exists)known.push(d);});return known;}
function draw(){var a=areas(),img='campus-uteq.jpg',shapes=a.map(function(x,i){return '<polygon class="campus-hotspot '+(i===selected?'selected':'')+'" points="'+DIN.esc(x.points)+'" data-area="'+i+'"><title>'+DIN.esc(x.name)+'</title></polygon>';}).join(''),labels=a.filter(function(x){return x.label;}).map(function(x){var text=x.label.text||x.name,w=Math.max(112,Math.min(230,72+String(text).length*12));return '<g class="campus-label"><rect x="'+(x.label.x-w/2)+'" y="'+(x.label.y-27)+'" width="'+w+'" height="48" rx="14"/><text x="'+x.label.x+'" y="'+x.label.y+'">'+DIN.esc(text)+'</text></g>';}).join('');$('campusCanvas').style.width=(scale*100)+'%';$('campusCanvas').innerHTML='<svg class="campus-svg" viewBox="0 0 1536 1536" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet"><image href="'+img+'" x="0" y="0" width="1536" height="1536" preserveAspectRatio="xMidYMid meet"/>'+shapes+labels+'</svg>';$('campusList').innerHTML=a.map(function(x,i){var b=buildingFor(x);return '<button type="button" class="'+(i===selected?'active':'')+'" data-campus-item="'+i+'"><strong>'+DIN.esc(b?model.buildingLabel(b):x.name)+'</strong></button>';}).join('');info();}
function info(){var a=areas()[selected],box=$('campusInfo');if(!a){box.innerHTML='<p class="muted">Selecciona un edificio para ver sus plantas y salones.</p>';return;}var b=buildingFor(a);if(!b){box.innerHTML='<h3>'+DIN.esc(a.name)+'</h3><p class="muted">Este punto del campus aún no está vinculado con un edificio activo.</p>';return;}var rs=model.rooms.filter(function(r){return model.building(r.edificio)&&model.building(r.edificio).id_edificio===b.id_edificio;}),floors=Array.from(new Set(rs.map(function(r){return r.planta;}))).sort(function(x,y){return DIN.natural(DIN.floorRank(x),DIN.floorRank(y));});box.innerHTML='<h3>'+DIN.esc(model.buildingLabel(b))+'</h3>'+floors.map(function(f){var n=rs.filter(function(r){return r.planta===f;}).length;return '<button type="button" class="soft" data-campus-floor="'+DIN.esc(f)+'">'+DIN.esc(f)+' · '+n+' espacios</button>';}).join(' ')+(floors.length?'':'<p class="muted">Sin aulas activas registradas.</p>');}
function open(){selected=-1;scale=1;draw();$('campusDialog').showModal();}
function setContext(s,m){snapshot=s;model=m;}
document.addEventListener('DOMContentLoaded',function(){var openBtn=$('openCampus');if(openBtn)openBtn.onclick=open;if($('closeCampus'))$('closeCampus').onclick=function(){$('campusDialog').close();};if($('campusCanvas'))$('campusCanvas').onclick=function(e){var p=e.target.closest('[data-area]');if(!p)return;selected=Number(p.dataset.area);draw();};if($('campusList'))$('campusList').onclick=function(e){var p=e.target.closest('[data-campus-item]');if(!p)return;selected=Number(p.dataset.campusItem);draw();};if($('campusInfo'))$('campusInfo').onclick=function(e){var b=e.target.closest('[data-campus-floor]');if(!b||selected<0||!root.DIN_PUBLIC)return;var a=areas()[selected],building=buildingFor(a);root.DIN_PUBLIC.openMapForBuilding(building.id_edificio,b.dataset.campusFloor);};if($('campusPlus'))$('campusPlus').onclick=function(){scale=Math.min(2.4,scale+.2);draw();};if($('campusMinus'))$('campusMinus').onclick=function(){scale=Math.max(.7,scale-.2);draw();};if($('campusFit'))$('campusFit').onclick=function(){scale=1;draw();};});
root.DIN_CAMPUS={setContext:setContext,open:open};
})(window);
