(function(root){
'use strict';
var KEY='din:2027:snapshot',TTL=10*60*1000;
function cached(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&x.payload?x:null;}catch(e){return null;}}
function store(p){try{localStorage.setItem(KEY,JSON.stringify({at:Date.now(),payload:p}));}catch(e){}}
function parseGviz(r){
 if(!r||r.status==='error'||!r.table)throw Error('PUBLIC_SNAPSHOT no disponible.');
 var cols=(r.table.cols||[]).map(function(c){return String(c.label||'').trim().toLowerCase();}),rows=(r.table.rows||[]).map(function(row){var o={};cols.forEach(function(k,i){var c=row.c[i];o[k]=c?(c.f!=null?c.f:c.v):'';});return o;});
 var active=rows.filter(function(x){return String(x.active).toLowerCase()==='true'||String(x.active)==='1';});if(!active.length)throw Error('No hay revisión pública activa.');
 var by={};active.forEach(function(x){var rev=String(x.revision||'');(by[rev]=by[rev]||[]).push(x);});
 var cand=Object.keys(by).map(function(rev){var a=by[rev].slice().sort(function(x,y){return Number(x.part)-Number(y.part);}),total=Number(a[0]&&a[0].total||0),ok=!!total&&a.length===total&&a.every(function(x,i){return Number(x.part)===i+1&&Number(x.total)===total;});return {rev:rev,a:a,ok:ok,updated:String(a[0]&&a[0].updated||'')};}).filter(function(x){return x.ok;});
 if(!cand.length)throw Error('PUBLIC_SNAPSHOT está incompleto.');cand.sort(function(a,b){return a.updated.localeCompare(b.updated);});var c=cand[cand.length-1],text=c.a.map(function(x){return String(x.chunk||'');}).join(''),p=JSON.parse(text);if(!p||![4,27,'27'].includes(p.api))throw Error('Versión pública no compatible.');return p;
}
function fromSheet(force){return new Promise(function(resolve,reject){var id=root.DIN_CONFIG&&root.DIN_CONFIG.sheetId;if(!id){reject(Error('Falta sheetId.'));return;}var cb='din27_'+Date.now()+'_'+Math.random().toString(36).slice(2),script=document.createElement('script'),done=false,t=setTimeout(function(){finish(Error('La hoja pública tardó demasiado.'));},10000);function finish(err,val){if(done)return;done=true;clearTimeout(t);try{script.remove();}catch(e){}try{delete root[cb];}catch(e){root[cb]=null;}err?reject(err):resolve(val);}root[cb]=function(r){try{finish(null,parseGviz(r));}catch(e){finish(e);}};script.onerror=function(){finish(Error('No se pudo leer PUBLIC_SNAPSHOT.'));};script.src='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(id)+'/gviz/tq?sheet=PUBLIC_SNAPSHOT&headers=1&tqx=responseHandler:'+cb+(force?'&_='+Date.now():'');document.head.appendChild(script);});}
function fromApi(force){return new Promise(function(resolve,reject){try{var u=new URL(root.DIN_CONFIG.endpoint);u.searchParams.set('action','snapshot');if(force)u.searchParams.set('_',Date.now());fetch(u.href,{credentials:'omit',cache:force?'no-store':'default'}).then(function(r){if(!r.ok)throw Error('Servicio público no disponible.');return r.json();}).then(function(x){if(!x||!x.ok||!x.snapshot)throw Error(x&&x.error||'Respuesta pública inválida.');resolve(x.snapshot);}).catch(reject);}catch(e){reject(e);}});}
async function load(force){var old=cached();if(!force&&old&&Date.now()-old.at<TTL)return {snapshot:old.payload,source:'cache',stale:false};try{var p=await fromSheet(!!force);store(p);return {snapshot:p,source:'sheet',stale:false};}catch(a){try{var q=await fromApi(!!force);store(q);return {snapshot:q,source:'api',stale:false,warning:'La consulta usó el servicio alterno porque PUBLIC_SNAPSHOT aún no estaba disponible.'};}catch(b){if(old)return {snapshot:old.payload,source:'cache',stale:true,warning:'Sin conexión: se muestra la última copia confirmada de este dispositivo.'};throw a;}}}
root.DIN27_SOURCE={load:load};
})(window);
