(function(root){'use strict';
var DIN=root.DIN,snapshot=null,model=null,selected=-1,scale=1;
// Coordenadas históricas capturadas sobre campus-uteq.jpg (1408 × 1787).
// R8: las etiquetas se colocan en el centro visual del polígono del edificio y siguen la orientación del plano.
var baseline=[
{id:'NANO_H1',name:'Nano',aliases:['N','NANO (H1)','NANO_H1','H1','NANO'],points:'645,896 763,845 791,905 672,959',label:{x:715,y:872,text:'NANO',width:118,angle:-23}},
{id:'AMBIENTAL_H',name:'H · Ambiental',aliases:['AMBIENTAL (H)','AMBIENTAL_H','H'],points:'714,995 847,940 875,1004 742,1060',label:{x:793,y:968,text:'H · Ambiental',width:178,angle:-23}},
{id:'I',name:'I',aliases:['I'],points:'768,1137 906,1078 930,1134 791,1194',label:{x:850,y:1110,text:'I',width:82,angle:-23}},
{id:'F',name:'F',aliases:['F'],points:'958,1270 1092,1217 1119,1277 989,1336',label:{x:1040,y:1246,text:'F',width:82,angle:-23}},
{id:'G',name:'G',aliases:['G'],points:'955,922 1088,866 1115,932 980,987',label:{x:1035,y:897,text:'G',width:82,angle:-23}},
{id:'CIC',name:'CIC 4.0',aliases:['CIC','CIC 4.0'],points:'920,414 948,369 934,340 1034,298 1065,256 1106,269 1076,318 1090,345 1000,380 956,431',label:{x:1012,y:340,text:'CIC 4.0',width:142,angle:-23}},
{id:'PIDET',name:'PIDET',aliases:['PIDET'],points:'901,242 932,194 916,168 1025,123 1048,85 1090,96 1070,139 1090,172 984,215 939,260',label:{x:996,y:164,text:'PIDET',width:132,angle:-23}},
{id:'D',key:'7EE',name:'7EE',aliases:['7EE','7E-E','Laboratorio 7E-E','D'],reference:true,points:'817,1430 961,1375 988,1435 842,1495',label:{x:902,y:1425,text:'7EE',width:98,angle:-23}},
{id:'E',key:'4EE',name:'4EE',aliases:['4EE','4E-E','Laboratorio 4E-E','E'],reference:true,points:'1003,1392 1080,1360 1107,1422 1030,1454',label:{x:1060,y:1395,text:'4EE',width:98,angle:-23}}
];
function $(id){return document.getElementById(id);}
function buildingFor(a){if(!model)return null;return model.buildings.find(function(b){return DIN.norm(b.id_edificio)===DIN.norm(a.id);})||model.buildings.find(function(b){return (a.aliases||[]).some(function(x){return [b.id_edificio,b.nombre,b.nombre_completo].some(function(v){return DIN.norm(v)===DIN.norm(x);});});});}
function areas(){var dynamic=(snapshot&&snapshot.campusAreas||[]).filter(function(a){return a&&a.id_edificio&&a.points;}).map(function(a){var b=model&&model.buildings.find(function(x){return String(x.id_edificio)===String(a.id_edificio);});return {id:a.id_edificio,name:b?model.buildingLabel(b):(a.name||a.id_edificio),aliases:[a.id_edificio],points:a.points,label:a.label||null};});var known=baseline.slice();dynamic.forEach(function(d){var db=buildingFor(d),exists=known.some(function(b){var bb=buildingFor(b);return db&&bb&&db.id_edificio===bb.id_edificio;});if(!exists)known.push(d);});return known;}
function shapeMarkup(a,withData){return a.map(function(x,i){return '<polygon class="campus-hotspot '+(x.reference?'reference ':'')+(i===selected?'selected':'')+'" points="'+DIN.esc(x.points)+'" '+(withData?'data-area="'+i+'"':'')+'><title>'+DIN.esc(x.name)+'</title></polygon>';}).join('');}
function polygonCentroid(points){var pts=String(points||'').trim().split(/\s+/).map(function(p){var q=p.split(',').map(Number);return {x:q[0],y:q[1]};}).filter(function(p){return isFinite(p.x)&&isFinite(p.y)});if(!pts.length)return {x:0,y:0};var area=0,cx=0,cy=0;for(var i=0;i<pts.length;i++){var p=pts[i],q=pts[(i+1)%pts.length],cross=p.x*q.y-q.x*p.y;area+=cross;cx+=(p.x+q.x)*cross;cy+=(p.y+q.y)*cross}area*=.5;if(Math.abs(area)<.001)return {x:pts.reduce(function(v,p){return v+p.x},0)/pts.length,y:pts.reduce(function(v,p){return v+p.y},0)/pts.length};return {x:cx/(6*area),y:cy/(6*area)}}
function labelMarkup(a){return a.filter(function(x){return x.label;}).map(function(x){var l=x.label,text=l.text||x.name,w=Math.min(Number(l.width)||Math.max(82,62+String(text).length*9),168),ang=Number(l.angle);if(!isFinite(ang))ang=-23;var c=polygonCentroid(x.points),lx=isFinite(Number(l.centerX))?Number(l.centerX):c.x,ly=isFinite(Number(l.centerY))?Number(l.centerY):c.y;return '<g class="campus-label" transform="translate('+lx+' '+ly+') rotate('+ang+')"><rect x="'+(-w/2)+'" y="-17" width="'+w+'" height="34" rx="8"/><text x="0" y="1">'+DIN.esc(text)+'</text></g>';}).join('');}
function mapSvg(withData){var a=areas();return '<svg class="campus-svg" viewBox="0 0 1408 1787" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet"><image href="campus-uteq.jpg" x="0" y="0" width="1408" height="1787" preserveAspectRatio="none"/>'+shapeMarkup(a,withData)+labelMarkup(a)+'</svg>';}
function groupsForBuilding(b){if(!b||!model)return [];return model.groups.filter(function(g){return model.placements(g).some(function(p){return p.building&&p.building.id_edificio===b.id_edificio;});}).sort(function(a,b2){return DIN.natural(a.grupo,b2.grupo);});}
function floorGroups(b,floor){if(!b||!model)return [];var ids=new Set(model.rooms.filter(function(r){var rb=model.building(r.edificio);return rb&&rb.id_edificio===b.id_edificio&&DIN.norm(r.planta)===DIN.norm(floor);}).map(function(r){return r.id_aula;}));return model.groups.filter(function(g){return model.placements(g).some(function(p){return p.room&&ids.has(p.room.id_aula);});}).sort(function(a,b2){return DIN.natural(a.grupo,b2.grupo);});}
function draw(){var a=areas();$('campusCanvas').style.width=(scale*100)+'%';$('campusCanvas').innerHTML=mapSvg(true);$('campusList').innerHTML=a.map(function(x,i){var b=buildingFor(x);return '<button type="button" class="'+(i===selected?'active':'')+'" data-campus-item="'+i+'"><strong>'+DIN.esc(b?model.buildingLabel(b):x.name)+'</strong></button>';}).join('');info();}
function info(){var a=areas()[selected],box=$('campusInfo');if(!a){box.innerHTML='<p class="muted">Selecciona un edificio para ver sus plantas y los grupos ubicados en él.</p>';return;}var b=buildingFor(a);if(!b){box.innerHTML='<h3>'+DIN.esc(a.name)+'</h3><p class="muted">'+(a.reference?'Referencia permanente de la División Industrial. Se mantiene visible aunque actualmente no tenga grupos asignados.':'Este punto aún no está vinculado con un edificio activo.')+'</p>';return;}var rs=model.rooms.filter(function(r){var rb=model.building(r.edificio);return rb&&rb.id_edificio===b.id_edificio;}),floors=Array.from(new Set(rs.map(function(r){return r.planta;}))).sort(function(x,y){return DIN.natural(DIN.floorRank(x),DIN.floorRank(y));}),allGroups=groupsForBuilding(b);box.innerHTML='<h3>'+DIN.esc(model.buildingLabel(b))+'</h3><p class="muted">'+allGroups.length+' grupos ubicados · '+rs.length+' espacios registrados</p>'+floors.map(function(f){var fg=floorGroups(b,f),rooms=rs.filter(function(r){return DIN.norm(r.planta)===DIN.norm(f);});return '<section class="campus-floor-card"><div><strong>'+DIN.esc(f)+'</strong><small>'+rooms.length+' espacios</small></div><div class="campus-group-tags">'+(fg.length?fg.map(function(g){return '<span>'+DIN.esc(g.grupo)+'</span>';}).join(''):'<span class="empty-tag">Sin grupos</span>')+'</div><button type="button" class="soft" data-campus-floor="'+DIN.esc(f)+'">Ver croquis</button></section>';}).join('')+(floors.length?'':'<p class="muted">Sin aulas activas registradas.</p>');}
function indexForKey(key){var k=DIN.norm(key);return areas().findIndex(function(a){return DIN.norm(a.id)===k||DIN.norm(a.key)===k||DIN.norm(a.name)===k||(a.aliases||[]).some(function(v){return DIN.norm(v)===k;});});}
function open(key){selected=key?indexForKey(key):-1;if(selected<0)selected=-1;scale=1;draw();$('campusDialog').showModal();}
function previewMarkup(){return '<button type="button" class="campus-inline-preview" data-open-campus aria-label="Abrir mapa completo del campus">'+mapSvg(false)+'<span>Abrir mapa interactivo del campus</span></button>';}
function setContext(s,m){snapshot=s;model=m;}
function activateHero(el){if(!el)return;open(el.getAttribute('data-hero-area'));}
document.addEventListener('DOMContentLoaded',function(){var openBtn=$('openCampus');if(openBtn)openBtn.onclick=function(){open();};var hero=document.querySelector('.hero-campus');if(hero){hero.addEventListener('click',function(e){var p=e.target.closest('[data-hero-area]');if(p)activateHero(p);});hero.addEventListener('keydown',function(e){var p=e.target.closest('[data-hero-area]');if(p&&(e.key==='Enter'||e.key===' ')){e.preventDefault();activateHero(p);}});}if($('closeCampus'))$('closeCampus').onclick=function(){$('campusDialog').close();};if($('campusCanvas'))$('campusCanvas').onclick=function(e){var p=e.target.closest('[data-area]');if(!p)return;selected=Number(p.dataset.area);draw();};if($('campusList'))$('campusList').onclick=function(e){var p=e.target.closest('[data-campus-item]');if(!p)return;selected=Number(p.dataset.campusItem);draw();};if($('campusInfo'))$('campusInfo').onclick=function(e){var btn=e.target.closest('[data-campus-floor]');if(!btn||selected<0||!root.DIN_PUBLIC)return;var a=areas()[selected],building=buildingFor(a);if(building)root.DIN_PUBLIC.openMapForBuilding(building.id_edificio,btn.dataset.campusFloor);};if($('campusPlus'))$('campusPlus').onclick=function(){scale=Math.min(2.4,scale+.2);draw();};if($('campusMinus'))$('campusMinus').onclick=function(){scale=Math.max(.7,scale-.2);draw();};if($('campusFit'))$('campusFit').onclick=function(){scale=1;draw();};});
root.DIN_CAMPUS={setContext:setContext,open:open,previewMarkup:previewMarkup};
})(window);
