(function(root){
'use strict';
var DIN=root.DIN27,snapshot=null,model=null,selected=-1,scale=1;
var baseline=[
{id:'NANO_H1',name:'Nano',aliases:['N','NANO (H1)','NANO_H1','H1','NANO'],points:'645,896 763,845 791,905 672,959',label:{x:717,y:901,text:'Nano',width:130}},
{id:'AMBIENTAL_H',name:'H · Ambiental',aliases:['AMBIENTAL (H)','AMBIENTAL_H','H'],points:'714,995 847,940 875,1004 742,1060',label:{x:794,y:1000,text:'H',width:95}},
{id:'I',name:'I',aliases:['I'],points:'768,1137 906,1078 930,1134 791,1194',label:{x:849,y:1136,text:'I',width:90}},
{id:'F',name:'F',aliases:['F'],points:'958,1270 1092,1217 1119,1277 989,1336',label:{x:1040,y:1274,text:'F',width:90}},
{id:'G',name:'G',aliases:['G'],points:'955,922 1088,866 1115,932 980,987',label:{x:1035,y:926,text:'G',width:90}},
{id:'CIC',name:'CIC 4.0',aliases:['CIC','CIC 4.0'],points:'920,414 948,369 934,340 1034,298 1065,256 1106,269 1076,318 1090,345 1000,380 956,431',label:{x:1014,y:344,text:'CIC 4.0',width:160}},
{id:'PIDET',name:'PIDET',aliases:['PIDET'],points:'901,242 932,194 916,168 1025,123 1048,85 1090,96 1070,139 1090,172 984,215 939,260',label:{x:999,y:168,text:'PIDET',width:155}}
];
function $(id){return document.getElementById(id);}
function buildingFor(a){if(!model)return null;return model.buildings.find(function(b){return DIN.norm(b.id_edificio)===DIN.norm(a.id);})||model.buildings.find(function(b){return (a.aliases||[]).some(function(x){return [b.id_edificio,b.nombre,b.nombre_completo].some(function(v){return DIN.norm(v)===DIN.norm(x);});});});}
function areas(){var dynamic=(snapshot&&snapshot.campusAreas||[]).filter(function(a){return a&&a.id_edificio&&a.points;}).map(function(a){var b=model&&model.buildings.find(function(x){return String(x.id_edificio)===String(a.id_edificio);});return {id:a.id_edificio,name:b?model.buildingLabel(b):(a.name||a.id_edificio),aliases:[a.id_edificio],points:a.points,label:a.label||null};});return baseline.filter(function(b){return !dynamic.some(function(d){var db=buildingFor(d),bb=buildingFor(b);return db&&bb&&db.id_edificio===bb.id_edificio;});}).concat(dynamic);}
function draw(){var a=areas(),shapes=a.map(function(x,i){return x.points?'<polygon class="campus-hotspot '+(i===selected?'selected':'')+'" points="'+DIN.esc(x.points)+'" data-area="'+i+'"><title>'+DIN.esc(x.name)+'</title></polygon>':'';}).join(''),labels=a.filter(function(x){return x.label;}).map(function(x){var l=x.label;return '<g class="campus-label" pointer-events="none" transform="translate('+Number(l.x)+' '+Number(l.y)+') rotate(-23)"><rect x="'+(-Number(l.width||100)/2)+'" y="-22" width="'+Number(l.width||100)+'" height="44" rx="6"/><text text-anchor="middle" dominant-baseline="middle" font-size="26">'+DIN.esc(l.text||x.name)+'</text></g>';}).join('');$('campusCanvas').innerHTML='<svg viewBox="0 0 1408 1787" xmlns="http://www.w3.org/2000/svg"><image href="campus-uteq.jpg" width="1408" height="1787" preserveAspectRatio="none"/>'+shapes+labels+'</svg>';$('campusCanvas').style.width=(scale*100)+'%';$('campusList').innerHTML=a.map(function(x,i){return '<button type="button" data-building="'+i+'" class="'+(i===selected?'selected':'')+'">'+DIN.esc(x.name)+'</button>';}).join('');}
function summary(i){selected=i;draw();var a=areas()[i],b=buildingFor(a);if(!b){$('campusInfo').innerHTML='<h3>'+DIN.esc(a.name)+'</h3><p>Edificio registrado sin catálogo académico asociado.</p>';return;}var rooms=model.rooms.filter(function(r){var rb=model.building(r.edificio);return rb&&rb.id_edificio===b.id_edificio;}),groups=model.groups.filter(function(g){return model.placements(g).some(function(p){return p.building.id_edificio===b.id_edificio;});}),floors=Array.from(new Set(rooms.map(function(r){return DIN.str(r.planta);}))).sort(DIN.natural);$('campusInfo').innerHTML='<h3>'+DIN.esc(model.buildingLabel(b))+'</h3><p>'+groups.length+' grupos · '+rooms.length+' aulas</p><div class="floor-buttons">'+floors.map(function(f){return '<button type="button" data-floor="'+DIN.esc(f)+'">'+DIN.esc(f)+'</button>';}).join('')+'</div><div id="campusFloorDetail"></div>';}
function floorDetail(f){var a=areas()[selected],b=buildingFor(a);if(!b)return;var rooms=model.rooms.filter(function(r){var rb=model.building(r.edificio);return rb&&rb.id_edificio===b.id_edificio&&DIN.norm(r.planta)===DIN.norm(f);});$('campusFloorDetail').innerHTML='<h4>'+DIN.esc(f)+'</h4><ul>'+rooms.map(function(r){var gs=model.groups.filter(function(g){return model.placements(g).some(function(p){return p.room.id_aula===r.id_aula;});});return '<li><strong>'+DIN.esc(model.roomLabel(r))+'</strong> — '+DIN.esc(gs.map(function(g){return g.grupo;}).join(', ')||'Sin grupo asignado')+'</li>';}).join('')+'</ul><button type="button" class="primary" id="openCampusPlan">Ver croquis</button>';var btn=$('openCampusPlan');if(btn)btn.onclick=function(){root.DIN27_APP.openMapForBuilding(b.id_edificio,f);};}
function open(){selected=-1;scale=1;draw();$('campusInfo').innerHTML='<h3>Elige un edificio</h3><p>Consulta sus plantas, aulas y grupos.</p>';$('campusDialog').showModal();}
function setContext(s,m){snapshot=s;model=m;}
document.addEventListener('DOMContentLoaded',function(){if($('openCampus'))$('openCampus').onclick=open;if($('closeCampus'))$('closeCampus').onclick=function(){$('campusDialog').close();};if($('campusList'))$('campusList').onclick=function(e){var b=e.target.closest('[data-building]');if(b)summary(Number(b.getAttribute('data-building')));};if($('campusCanvas'))$('campusCanvas').onclick=function(e){var p=e.target.closest('[data-area]');if(p)summary(Number(p.getAttribute('data-area')));};if($('campusInfo'))$('campusInfo').onclick=function(e){var f=e.target.closest('[data-floor]');if(f)floorDetail(f.getAttribute('data-floor'));};if($('campusPlus'))$('campusPlus').onclick=function(){scale=Math.min(3,scale+.5);draw();};if($('campusMinus'))$('campusMinus').onclick=function(){scale=Math.max(1,scale-.5);draw();};if($('campusFit'))$('campusFit').onclick=function(){scale=1;draw();};});
root.DIN27_CAMPUS={setContext:setContext,open:open};
})(window);
