(function(root){'use strict';
var KEY='din:final:snapshot',TTL=0;
function cached(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&x.payload?x:null;}catch(e){return null;}}
function store(p){try{localStorage.setItem(KEY,JSON.stringify({at:Date.now(),payload:p}));}catch(e){}}
function normalizeSnapshot(p){if(!p||!p.data)throw Error('Publicación inválida.');if(!p.active&&p.publicPeriod)p.active=p.publicPeriod;return p;}
function parseGviz(r){
 if(!r||r.status==='error'||!r.table)throw Error('PUBLIC_SNAPSHOT no disponible.');
 var cols=(r.table.cols||[]).map(function(c){return String(c.label||'').trim().toLowerCase();});
 var rows=(r.table.rows||[]).map(function(row){var o={};cols.forEach(function(k,i){var c=row.c[i];o[k]=c?(c.f!=null?c.f:c.v):'';});return o;});
 var active=rows.filter(function(x){return String(x.active).toLowerCase()==='true'||String(x.active)==='1';});if(!active.length)throw Error('No hay revisión pública activa.');
 var by={};active.forEach(function(x){var rev=String(x.revision||'');(by[rev]=by[rev]||[]).push(x);});
 var cand=Object.keys(by).map(function(rev){var a=by[rev].slice().sort(function(x,y){return Number(x.part)-Number(y.part);}),total=Number(a[0]&&a[0].total||0),ok=!!total&&a.length===total&&a.every(function(x,i){return Number(x.part)===i+1&&Number(x.total)===total;});return {rev:rev,a:a,ok:ok,updated:String(a[0]&&a[0].updated||'')};}).filter(function(x){return x.ok;});
 if(!cand.length)throw Error('PUBLIC_SNAPSHOT está incompleto.');cand.sort(function(a,b){return a.updated.localeCompare(b.updated);});var c=cand[cand.length-1],text=c.a.map(function(x){return String(x.chunk||'');}).join('');return normalizeSnapshot(JSON.parse(text));
}
function fromSheet(force){return new Promise(function(resolve,reject){var id=root.DIN_CONFIG&&root.DIN_CONFIG.sheetId;if(!id){reject(Error('Falta sheetId.'));return;}var cb='dinFinal_'+Date.now()+'_'+Math.random().toString(36).slice(2),script=document.createElement('script'),done=false,t=setTimeout(function(){finish(Error('La hoja pública tardó demasiado.'));},7000);function finish(err,val){if(done)return;done=true;clearTimeout(t);try{script.remove();}catch(e){}try{delete root[cb];}catch(e){root[cb]=null;}err?reject(err):resolve(val);}root[cb]=function(r){try{finish(null,parseGviz(r));}catch(e){finish(e);}};script.onerror=function(){finish(Error('No se pudo leer PUBLIC_SNAPSHOT.'));};script.src='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(id)+'/gviz/tq?sheet=PUBLIC_SNAPSHOT&headers=1&tqx=responseHandler:'+cb+'&_='+Date.now();document.head.appendChild(script);});}
function fromApi(force){return new Promise(function(resolve,reject){try{var u=new URL(root.DIN_CONFIG.endpoint);u.searchParams.set('action','snapshot');if(force)u.searchParams.set('_',Date.now());var ctl=window.AbortController?new AbortController():null,t=setTimeout(function(){if(ctl)ctl.abort();reject(Error('El servicio tardó demasiado.'));},8000);fetch(u.href,{credentials:'omit',cache:'no-store',signal:ctl&&ctl.signal}).then(function(r){if(!r.ok)throw Error('Servicio público no disponible.');return r.json();}).then(function(x){clearTimeout(t);if(!x||!x.ok||!x.snapshot)throw Error(x&&x.error||'Respuesta pública inválida.');resolve(normalizeSnapshot(x.snapshot));}).catch(function(e){clearTimeout(t);reject(e);});}catch(e){reject(e);}});}
async function load(force){var old=cached();if(!force&&old&&Date.now()-old.at<TTL)return {snapshot:old.payload,source:'cache',stale:false};if(force){try{var api=await fromApi(true);store(api);return {snapshot:api,source:'api',stale:false};}catch(apiErr){try{var sh=await fromSheet(true);store(sh);return {snapshot:sh,source:'sheet',stale:false,warning:'El servicio directo no respondió; se leyó la copia pública de Google Sheets.'};}catch(shErr){if(old)return {snapshot:old.payload,source:'cache',stale:true,warning:'No fue posible actualizar; se muestra la última publicación confirmada.'};throw shErr;}}}try{var p=await fromSheet(false);store(p);return {snapshot:p,source:'sheet',stale:false};}catch(a){try{var q=await fromApi(false);store(q);return {snapshot:q,source:'api',stale:false,warning:'Se usó el servicio alterno porque la copia pública optimizada no respondió.'};}catch(b){if(old)return {snapshot:old.payload,source:'cache',stale:true,warning:'Sin conexión: se muestra la última publicación confirmada guardada en este dispositivo.'};throw b;}}}
root.DIN_SOURCE={load:load};
})(window);
