(function(root){
'use strict';
var DIN=root.DIN27,$=function(id){return document.getElementById(id);},snapshot=null,model=null,mode='groups',plans=Array.isArray(root.DIN_PLANOS)?root.DIN_PLANOS.slice():[],currentPlan=null,currentRoomId='',scale=1;
function mergePlans(dynamic){dynamic=Array.isArray(dynamic)?dynamic:[];return plans.filter(function(p){return !dynamic.some(function(q){return q.id===p.id||(q.edificio===p.edificio&&DIN.norm(q.planta)===DIN.norm(p.planta));});}).concat(dynamic);}
function empty(title,text){return '<div class="empty"><strong>'+DIN.esc(title)+'</strong><span>'+DIN.esc(text||'')+'</span></div>';}
function periodId(){return model&&model.period?model.period.id_periodo:'';}
function refreshStats(){
 $('statGroups').textContent=model.groups.length;$('statTutors').textContent=new Set(model.groups.filter(function(g){return DIN.hasTutor(g.tutor);}).map(function(g){return DIN.norm(g.tutor);})).size;$('statBuildings').textContent=model.buildings.length;$('statRooms').textContent=model.rooms.length;
 root.DIN27_SCHEDULES.ensureManifest(periodId()).then(function(m){$('statTeachers').textContent=m&&m.profesores&&m.profesores.pages?m.profesores.pages.length:'—';});
}
function refreshCareer(){var old=$('career').value,names=Array.from(new Set(model.groups.map(function(g){return DIN.str(g.ingenieria);}).filter(Boolean))).sort(DIN.natural);$('career').innerHTML='<option value="">Todas las carreras</option>'+names.map(function(x){return '<option>'+DIN.esc(x)+'</option>';}).join('');if(names.indexOf(old)>=0)$('career').value=old;}
function matching(q){q=DIN.norm(q);var career=$('career').value;return model.groups.filter(function(g){if(career&&g.ingenieria!==career)return false;var txt=DIN.norm([g.grupo,g.tutor,g.correo,g.ingenieria,g.salida_lateral,g.generacion].join(' '));return q.split(' ').filter(Boolean).every(function(t){return txt.indexOf(t)>=0;});});}
function tile(g){return '<strong>'+DIN.esc(g.grupo)+'</strong><small>'+DIN.esc(g.ingenieria||'Carrera pendiente')+'</small>'+(g.cuatrimestre?'<small>'+DIN.esc(g.cuatrimestre)+'º cuatrimestre</small>':'')+(DIN.hasTutor(g.tutor)?'<small>Tutor: '+DIN.esc(g.tutor)+'</small>':'');}
function card(g){var ps=model.placements(g),mail=DIN.str(g.correo);return '<article class="group-card"><h3>'+DIN.esc(g.grupo)+'</h3><p>'+DIN.esc(g.ingenieria||'')+(g.salida_lateral?' · '+DIN.esc(g.salida_lateral):'')+'</p>'+(DIN.hasTutor(g.tutor)?'<div class="field"><small>TUTOR / TUTORA</small><strong>'+DIN.esc(g.tutor)+'</strong></div>':'<p class="notice">Tutor pendiente</p>')+'<div class="fields"><div class="field"><small>GENERACIÓN</small>'+DIN.esc(g.generacion||'—')+'</div><div class="field"><small>CORREO</small>'+(/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(mail)?'<a href="mailto:'+DIN.esc(mail)+'">'+DIN.esc(mail)+'</a>':'Pendiente')+'</div></div>'+(ps.length?ps.map(function(p){return '<div class="placement"><strong>'+DIN.esc(model.buildingLabel(p.building))+'</strong><p>Planta '+DIN.esc(p.room.planta)+' · '+DIN.esc(model.roomLabel(p.room))+' · '+DIN.esc(p.assignment.turno||'Turno no indicado')+'</p><button type="button" class="soft" data-room="'+DIN.esc(p.room.id_aula)+'">Ubicar aula</button></div>';}).join(''):'<p class="notice">Aula pendiente de asignación.</p>')+'</article>';}
function renderGroups(q){var gs=matching(q);$('resultTitle').textContent=mode==='locate'?'Localiza tu salón':'Grupos del periodo';$('count').textContent=gs.length+' grupos';$('results').innerHTML=gs.length?'<div class="group-grid">'+gs.map(function(g){return '<button type="button" class="group-tile" data-group="'+DIN.esc(g.id_grupo)+'">'+tile(g)+'</button>';}).join('')+'</div><div id="detail"></div>':empty('Sin coincidencias','Prueba otro código, tutor o carrera.');}
function renderTutors(q){var gs=matching(q),map=new Map();gs.forEach(function(g){if(DIN.hasTutor(g.tutor)){var k=DIN.norm(g.tutor);if(!map.has(k))map.set(k,[]);map.get(k).push(g);}});var arr=Array.from(map.values()).sort(function(a,b){return DIN.natural(a[0].tutor,b[0].tutor);});$('resultTitle').textContent='Tutores y grupos';$('count').textContent=arr.length+' tutores';$('results').innerHTML=arr.length?arr.map(function(x){return '<details class="tutor-card"><summary><strong>'+DIN.esc(x[0].tutor)+'</strong><span>'+x.length+' grupo(s)</span></summary><p>'+x.map(function(g){return '<button type="button" class="chip" data-group="'+DIN.esc(g.id_grupo)+'">'+DIN.esc(g.grupo)+'</button>';}).join(' ')+'</p></details>';}).join(''):empty('Sin tutores','No hay coincidencias.');}
function locate(g){var ps=model.placements(g);return '<article class="group-card"><h3>'+DIN.esc(g.grupo)+' · Localiza tu salón</h3>'+(ps.length?ps.map(function(p){return '<ol class="location"><li><small>Edificio</small><strong>'+DIN.esc(model.buildingLabel(p.building))+'</strong></li><li><small>Planta</small><strong>'+DIN.esc(p.room.planta)+'</strong></li><li><small>Aula</small><strong>'+DIN.esc(model.roomLabel(p.room))+'</strong></li></ol><button class="primary" data-room="'+DIN.esc(p.room.id_aula)+'">Abrir croquis</button>';}).join(''):'<p>Aula pendiente.</p>')+'</article>';}
function render(){if(!model)return;var q=$('search').value;$('clear').hidden=!q;if(['profesores','grupos','salones'].indexOf(mode)>=0){$('academic').hidden=true;$('schedules').hidden=false;root.DIN27_SCHEDULES.mount(mode,$('schedules'));return;}$('academic').hidden=false;$('schedules').hidden=true;if(mode==='tutors')renderTutors(q);else renderGroups(q);}
function drawPlan(){if(!currentPlan)return;var w=Number(currentPlan.width||900),h=Number(currentPlan.height||400),svg='<svg viewBox="0 0 '+w+' '+h+'" xmlns="http://www.w3.org/2000/svg">';if(currentPlan.background)svg+='<image href="'+DIN.esc(currentPlan.background)+'" width="'+w+'" height="'+h+'" preserveAspectRatio="none"/>';(currentPlan.spaces||[]).forEach(function(s){var selected=currentRoomId&&(String(s.roomId||'')===String(currentRoomId)||model.roomById(currentRoomId)&&model.geometry(model.roomById(currentRoomId))&&model.geometry(model.roomById(currentRoomId)).space===s),fill=selected?'#f3d762':(s.kind==='room'?'#dcefe8':'#e9edef'),stroke=selected?'#826600':'#76929f';if(Array.isArray(s.points)&&s.points.length>=3)svg+='<polygon points="'+s.points.map(function(p){return p[0]+','+p[1];}).join(' ')+'" fill="'+fill+'" stroke="'+stroke+'" stroke-width="2"/>';else svg+='<rect x="'+Number(s.x||0)+'" y="'+Number(s.y||0)+'" width="'+Number(s.w||1)+'" height="'+Number(s.h||1)+'" rx="4" fill="'+fill+'" stroke="'+stroke+'" stroke-width="2"/>';svg+='<text x="'+(Number(s.x||0)+Number(s.w||1)/2)+'" y="'+(Number(s.y||0)+Number(s.h||1)/2)+'" text-anchor="middle" dominant-baseline="middle" font-size="11" fill="#294b59">'+DIN.esc(s.label||s.key)+'</text>';});svg+='</svg>';$('mapCanvas').innerHTML=svg;$('mapCanvas').style.width=(scale*100)+'%';}
function openPlan(){if(!currentPlan)return;var b=model.buildings.find(function(x){return x.id_edificio===currentPlan.edificio;});$('mapTitle').textContent=b?model.buildingLabel(b):currentPlan.edificio;var same=model.plans.filter(function(p){return p.edificio===currentPlan.edificio;});$('floor').innerHTML=same.map(function(p){return '<option value="'+DIN.esc(p.id)+'">'+DIN.esc(p.planta)+'</option>';}).join('');$('floor').value=currentPlan.id;drawPlan();$('mapDialog').showModal();}
function openRoom(id){var r=model.roomById(id);if(!r)return;var geo=model.geometry(r);if(!geo){alert('El aula está registrada, pero no pudo relacionarse con un croquis. Revisa la posición del aula en Administración.');return;}currentPlan=geo.plan;currentRoomId=r.id_aula;scale=1;openPlan();}
function openMapForBuilding(id,floor){var p=model.plans.find(function(x){return x.edificio===id&&(!floor||DIN.norm(x.planta)===DIN.norm(floor));});if(!p){alert('Croquis pendiente para esta planta.');return;}currentPlan=p;currentRoomId='';scale=1;openPlan();}
async function start(force){$('refresh').disabled=true;$('connection').textContent='Conectando…';$('status').textContent='Actualizando información…';try{var r=await root.DIN27_SOURCE.load(!!force);snapshot=r.snapshot;model=DIN.model(snapshot,snapshot.active,mergePlans(snapshot.plans||[]));model.plans=mergePlans(snapshot.plans||[]);root.DIN27_SCHEDULES.setContext(snapshot,model);root.DIN27_CAMPUS.setContext(snapshot,model);$('period').innerHTML=model.periods.map(function(p){return '<option value="'+DIN.esc(p.id_periodo)+'">'+DIN.esc(p.nombre)+'</option>';}).join('');$('period').value=model.period&&model.period.id_periodo||'';$('period').disabled=model.periods.length<2;$('connection').textContent=r.stale?'Copia confirmada':'Datos actualizados';$('status').textContent=r.warning||'';var d=new Date(snapshot.updated||'');$('updated').textContent=isFinite(d.getTime())?'Actualización: '+d.toLocaleString('es-MX'):' ';refreshCareer();refreshStats();render();}catch(e){$('connection').textContent='Sin conexión';$('status').textContent=e.message||'No se pudo cargar la consulta.';$('status').className='status error';$('results').innerHTML=empty('Información no disponible','Intenta nuevamente.');}finally{$('refresh').disabled=false;}}
function selectMode(m){mode=m;document.querySelectorAll('[data-mode]').forEach(function(b){var on=b.dataset.mode===m;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on?'true':'false');});render();}
document.addEventListener('DOMContentLoaded',function(){$('refresh').onclick=function(){start(true);};$('search').oninput=render;$('career').onchange=render;$('clear').onclick=function(){$('search').value='';render();};$('period').onchange=function(){model=DIN.model(snapshot,$('period').value,mergePlans(snapshot.plans||[]));root.DIN27_SCHEDULES.setContext(snapshot,model);root.DIN27_CAMPUS.setContext(snapshot,model);refreshCareer();refreshStats();render();};document.querySelector('.tabs').onclick=function(e){var b=e.target.closest('[data-mode]');if(b)selectMode(b.dataset.mode);};$('results').onclick=function(e){var g=e.target.closest('[data-group]'),r=e.target.closest('[data-room]');if(r)openRoom(r.dataset.room);else if(g){var x=model.groupById(g.dataset.group),d=$('detail');if(d){d.innerHTML=mode==='locate'?locate(x):card(x);d.scrollIntoView({behavior:'smooth',block:'nearest'});}}};$('closeMap').onclick=function(){$('mapDialog').close();};$('floor').onchange=function(){currentPlan=model.plans.find(function(p){return p.id===$('floor').value;})||currentPlan;currentRoomId='';drawPlan();};$('zoomIn').onclick=function(){scale=Math.min(3,scale+.25);drawPlan();};$('zoomOut').onclick=function(){scale=Math.max(.75,scale-.25);drawPlan();};$('zoomReset').onclick=function(){scale=1;drawPlan();};start(false);});
root.DIN27_APP={periodId:periodId,openRoom:openRoom,openMapForBuilding:openMapForBuilding};
})(window);
