(function(root){'use strict';
function str(v){return String(v==null?'':v).trim();}
function norm(v){var x=str(v);try{x=x.normalize('NFD').replace(/[\u0300-\u036f]/g,'');}catch(e){}return x.toLowerCase().replace(/\s+/g,' ');}
function compact(v){return norm(v).replace(/[^a-z0-9]/g,'');}
function slug(v){return norm(v).replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'').toUpperCase();}
function active(v){return v===true||['true','verdadero','1','si','sí'].indexOf(norm(v))>=0;}
function esc(v){return str(v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function natural(a,b){return str(a).localeCompare(str(b),'es',{numeric:true,sensitivity:'base'});}
function floorRank(v){var x=norm(v).replace(/^planta /,'');if(x==='baja'||x==='pb')return '00';if(x==='alta'||x==='pa')return '01';var m=x.match(/(?:nivel|piso)\s*(\d+)/);return m?'02-'+String(Number(m[1])).padStart(3,'0'):'03-'+x;}
function isPending(v){var x=norm(v);return !x||['-','--','—','pendiente','sin asignar','no asignado','no asignada','n/a','na','null','edif-'].indexOf(x)>=0;}
function hasTutor(v){var x=norm(v);return !!x&&['sin tutor','sin tutora','sin asignar','no asignado','no asignada','pendiente','pendiente de asignacion','pendiente de captura','fusion','fusión','n/a','na','ninguno','ninguna','0','-','—'].indexOf(x)<0;}
function specialGroup(g){var x=norm(g&&g.cuatrimestre);if(x.indexOf('titul')>=0)return 'TITULACIÓN';if(x.indexOf('estad')>=0)return 'ESTADÍA';return '';}
function careerKey(v){var x=norm(v);if(x.indexOf('nano')>=0)return 'nano';if(x.indexOf('manten')>=0)return 'maintenance';if(x.indexOf('autom')>=0)return 'automotive';if(x.indexOf('mecan')>=0)return 'mechanical';if(x.indexOf('indus')>=0)return 'industrial';return 'default';}
function careerColor(v,snapshot){var key=careerKey(v),defaults={industrial:'#d4f1fc',mechanical:'#fadece',automotive:'#ffffcc',maintenance:'#ffd1d1',nano:'#ffe579',default:'#dcecf0'},cfg=snapshot&&snapshot.settings&&snapshot.settings.careerColors||{};return cfg[key]||defaults[key]||defaults.default;}
function email(v){return /^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(str(v));}
function timeText(v){var x=str(v);if(!x)return '';if(/^0?\.\d+$/.test(x)){var mins=Math.round(Number(x)*1440);if(mins>=0&&mins<1440)return String(Math.floor(mins/60)).padStart(2,'0')+':'+String(mins%60).padStart(2,'0');}return x;}
function professorName(p){if(!p)return '';var s=[p.apellido_paterno,p.apellido_materno,p.nombres].map(str).filter(Boolean).join(' ');return s||str(p.nombre_publico||p.nombre_completo||p.nombre_fuente||p.nombre||p.nombre_pdf);}
function teacherDisplay(source,snapshot){var raw=str(source),period=snapshot&&snapshot.active||'';var aliases=snapshot&&snapshot.teacherAliases&&snapshot.teacherAliases[period]||[];var a=aliases.find(function(x){return norm(x.sourceName||x.source_professor)===norm(raw);});if(a&&a.publicName)raw=a.publicName;var profs=(snapshot&&snapshot.data&&snapshot.data.PROFESORES)||snapshot&&snapshot.professors||[];var p=profs.find(function(x){return [x.nombre_pdf,x.nombre_fuente,x.nombre_completo,x.nombre_publico,x.nombre].some(function(v){return v&&norm(v)===norm(raw);});});return p?professorName(p):raw;}
function model(snapshot,periodId,plans){snapshot=snapshot||{};var data=snapshot.data||{};plans=Array.isArray(plans)?plans:(snapshot.plans||[]);var periods=(data.PERIODOS||[]).filter(function(p){return !active(p.archivado);});var period=periods.find(function(p){return str(p.id_periodo)===str(periodId);})||periods.find(function(p){return str(p.id_periodo)===str(snapshot.active);})||periods[0]||null;
 var groups=(data.GRUPOS||[]).filter(function(g){return period&&str(g.periodo)===str(period.id_periodo)&&(!Object.prototype.hasOwnProperty.call(g,'activo')||active(g.activo));}).sort(function(a,b){return natural(a.grupo,b.grupo);});
 var buildings=(data.EDIFICIOS||[]).filter(function(b){return !Object.prototype.hasOwnProperty.call(b,'activo')||active(b.activo);}).sort(function(a,b){return natural(buildingLabel(a),buildingLabel(b));});
 function buildingLabel(b){return str(b&&(b.nombre_completo||b.nombre||b.id_edificio));}
 function building(value){var k=compact(value),found=buildings.filter(function(b){return [b.id_edificio,b.nombre,b.nombre_completo].some(function(x){return compact(x)===k;});});return found.length===1?found[0]:null;}
 var rooms=(data.AULAS||[]).filter(function(r){return (!Object.prototype.hasOwnProperty.call(r,'activo')||active(r.activo))&&building(r.edificio);}).sort(function(a,b){return natural(buildingLabel(building(a.edificio)),buildingLabel(building(b.edificio)))||natural(floorRank(a.planta),floorRank(b.planta))||natural(roomLabel(a),roomLabel(b));});
 var assignments=(data.ASIGNACION_AULAS||[]).filter(function(a){return period&&str(a.periodo)===str(period.id_periodo)&&(!Object.prototype.hasOwnProperty.call(a,'activo')||active(a.activo));});
 var professors=(data.PROFESORES||[]).filter(function(p){return (!p.periodo||!period||str(p.periodo)===str(period.id_periodo))&&(!Object.prototype.hasOwnProperty.call(p,'activo')||active(p.activo));}).sort(function(a,b){return natural(professorName(a),professorName(b));});
 var tutoring=(data.TUTORIAS||[]).filter(function(t){return period&&str(t.periodo)===str(period.id_periodo)&&(!Object.prototype.hasOwnProperty.call(t,'activo')||active(t.activo));});
 function roomById(id){var x=rooms.filter(function(r){return str(r.id_aula)===str(id);});return x.length===1?x[0]:null;}
 function groupById(id){var x=groups.filter(function(g){return str(g.id_grupo)===str(id)||str(g.grupo)===str(id);});return x.length===1?x[0]:null;}
 function professorById(id){var x=professors.filter(function(p){return str(p.id_profesor)===str(id);});return x.length===1?x[0]:null;}
 function roomLabel(room){return str(room&&(room.nombre||room.salon||room.aula||room.id_aula));}
 function placements(g){return assignments.filter(function(a){return str(a.id_grupo)===str(g.id_grupo)||(!a.id_grupo&&norm(a.grupo)===norm(g.grupo));}).map(function(a){var r=roomById(a.id_aula);if(!r&&a.salon){var candidates=rooms.filter(function(x){var b=building(x.edificio);return norm(roomLabel(x))===norm(a.salon)&&(!a.planta||norm(x.planta)===norm(a.planta))&&(!a.edificio||b&&[b.id_edificio,b.nombre,b.nombre_completo].some(function(v){return compact(v)===compact(a.edificio);}));});if(candidates.length===1)r=candidates[0];}var b=r&&building(r.edificio);return r&&b?{assignment:a,room:r,building:b}:null;}).filter(Boolean);}
 function tutorForGroup(g){var t=tutoring.find(function(x){return str(x.id_grupo)===str(g.id_grupo)||norm(x.grupo)===norm(g.grupo);});if(t&&t.id_profesor){var p=professorById(t.id_profesor);if(p)return {name:professorName(p),email:p.correo||t.correo||'',professor:p};}if(t&&t.nombre)return {name:t.nombre,email:t.correo||'',professor:null};if(hasTutor(g.tutor)){var p2=professors.find(function(p){return norm(professorName(p))===norm(g.tutor)||norm(p.nombre_fuente)===norm(g.tutor);});return {name:g.tutor,email:g.correo||p2&&p2.correo||'',professor:p2||null};}return null;}
 function groupsForProfessor(p){var ids=new Set(tutoring.filter(function(t){return str(t.id_profesor)===str(p.id_profesor);}).map(function(t){return str(t.id_grupo);}));return groups.filter(function(g){return ids.has(str(g.id_grupo));});}
 function geometry(room){var b=building(room.edificio);if(!b)return null;var floor=norm(room.planta).replace(/^planta /,'');var p=plans.find(function(x){return str(x.edificio)===str(b.id_edificio)&&norm(x.planta).replace(/^planta /,'')===floor;});if(!p)return null;var id=str(room.id_aula),tail=id.split('-').pop(),label=roomLabel(room),keys=[room.posicion,id,tail,label,slug(label),slug(tail)].filter(Boolean).map(compact);var spaces=(p.spaces||[]).filter(function(s){var vals=[s.roomId,s.key,s.label].filter(Boolean).map(compact);return vals.some(function(v){return keys.indexOf(v)>=0;});});if(spaces.length===1)return {plan:p,space:spaces[0]};return null;}
 return {periods:periods,period:period,groups:groups,buildings:buildings,rooms:rooms,assignments:assignments,professors:professors,tutoring:tutoring,plans:plans,building:building,buildingLabel:buildingLabel,roomById:roomById,roomLabel:roomLabel,groupById:groupById,professorById:professorById,professorName:professorName,placements:placements,tutorForGroup:tutorForGroup,groupsForProfessor:groupsForProfessor,geometry:geometry};
}
root.DIN={str:str,norm:norm,compact:compact,slug:slug,active:active,esc:esc,natural:natural,floorRank:floorRank,isPending:isPending,hasTutor:hasTutor,specialGroup:specialGroup,careerKey:careerKey,careerColor:careerColor,email:email,timeText:timeText,professorName:professorName,teacherDisplay:teacherDisplay,model:model};
})(window);
