const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const ctx={Session:{getActiveUser:()=>({getEmail:()=>email})},PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'other@uteq.edu.mx'})},normalizar_:v=>String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')};
let email='other@uteq.edu.mx';vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../Administracion.gs'),'utf8'),ctx);
const state={data:{PERIODOS:[{id_periodo:'2027-1',nombre:'Enero',activo:'TRUE'}],GRUPOS:[{id_grupo:'old',grupo:'OLD',periodo:'2026-3',tutor:''}],EDIFICIOS:[{id_edificio:'ED-F',nombre:'F',activo:'TRUE'}],AULAS:[{id_aula:'F-ALTA-1',nombre:'1',planta:'ALTA',edificio:'ED-F',activo:'TRUE',posicion:'1'}],ASIGNACION_AULAS:[{periodo:'2026-3',id_grupo:'old',id_aula:'F-ALTA-1',turno:'Matutino',activo:'TRUE'}]}};
const base={grupo:'LII025',tutor:'Tutor',edificio:'F',planta:'ALTA',aula:'1',turno:'Matutino'};let n=0;function test(name,fn){fn();n++;console.log('PASS '+name);}
test('Solo el propietario incluso si otra cuenta figura en propiedades',()=>{assert.throws(()=>ctx.adminIdentity_(),/exclusiva/);email='';assert.throws(()=>ctx.adminIdentity_(),/Acceso denegado/);email='ivan.gutierrez@uteq.edu.mx';assert.equal(ctx.adminIdentity_(),email);});
test('Hoja única agrupa repetidos y conserva planos y otros periodos',()=>{const before=JSON.stringify(state),r=ctx.unifiedImport_(state,[base,{...base,grupo:'LII026'}],'2027-1',false);assert.deepEqual(Array.from(r.errors),[]);assert.equal(r.counts.edificios,1);assert.equal(r.counts.aulas,1);assert.equal(r.counts.grupos,2);assert.equal(r.counts.asignaciones,2);assert.equal(r.data.AULAS[0].posicion,'1');assert.equal(r.data.GRUPOS[0].periodo,'2026-3');assert.equal(r.data.ASIGNACION_AULAS[0].periodo,'2026-3');assert.equal(JSON.stringify(state),before);});
test('Detecta conflictos reales en edificios repetidos',()=>{const r=ctx.unifiedImport_(state,[{...base,nombre_edificio_completo:'Primero'},{...base,nombre_edificio_completo:'Segundo'}],'2027-1',false);assert.match(r.errors.join(' '),/Filas 2 y 3/);});
test('Permite grupo pendiente de ubicación y aulas sin grupo',()=>{const r=ctx.unifiedImport_(state,[{grupo:'PENDIENTE'}, {...base,grupo:''}],'2027-1',false);assert.equal(r.errors.length,0);assert.equal(r.pending,1);assert.equal(r.counts.asignaciones,0);});
test('Crear aula en otra planta conserva el catálogo existente',()=>{const r=ctx.unifiedImport_(state,[{edificio:'F',planta:'NIVEL 2',aula:'Laboratorio'}],'2027-1',true);assert.equal(r.errors.length,0);assert.equal(r.data.AULAS.length,2);assert.equal(r.data.GRUPOS.length,1);assert.equal(r.data.AULAS[1].planta,'NIVEL 2');});
test('Rechaza trasladar un ID de aula a otra planta',()=>{const r=ctx.unifiedImport_(state,[{...base,id_aula:'F-ALTA-1',planta:'BAJA'}],'2027-1',false);assert.match(r.errors.join(' '),/otro edificio o planta/);});
test('Rechaza periodo distinto, turno faltante y capacidad inválida',()=>{for(const patch of [{periodo:'2028-1'},{turno:''},{capacidad:'muchos'}])assert.ok(ctx.unifiedImport_(state,[{...base,...patch}],'2027-1',false).errors.length);});
test('Importación individual deduplica edificios iguales pero no conflictos',()=>{const b=state.data.EDIFICIOS[0];assert.equal(ctx.compactCatalog_('EDIFICIOS',[b,b]).length,1);assert.throws(()=>ctx.compactCatalog_('EDIFICIOS',[b,{...b,nombre:'otro'}]),/valores distintos/);});
test('Nombres y columnas adicionales no se copian al modelo público',()=>{const r=ctx.unifiedImport_(state,[{...base,'M.E. Cuatri.Z':'ignorar'}],'2027-1',false);assert.equal(r.errors.length,0);assert.ok(!JSON.stringify(r.data).includes('Cuatri'));});
console.log(n+' pruebas de administración correctas');
