/* Pruebas autónomas: node tests/run.cjs. No acceden a Google ni modifican datos reales. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),DIN=require(path.join(root,'datos.js'));
const data={PERIODOS:[{id_periodo:'2026-3',nombre:'Periodo de prueba',activo:'TRUE'}],GRUPOS:[{id_grupo:'G1',grupo:'TEST001',periodo:'2026-3',tutor:'Tutor de prueba'}],EDIFICIOS:[{id_edificio:'ED-F',nombre:'F',activo:'TRUE'}],AULAS:[{id_aula:'F-ALTA-1',edificio:'ED-F',planta:'ALTA',activo:'TRUE',nombre:'Salón 1',posicion:'1'}],ASIGNACION_AULAS:[{periodo:'2026-3',id_grupo:'G1',id_aula:'F-ALTA-1',turno:'Matutino',activo:'TRUE'}]};
const properties=new Map([['DIN_ADMINS','ivan.gutierrez@uteq.edu.mx'],['DIN_FOLDER','private-test-folder']]),files=new Map();let email='ivan.gutierrez@uteq.edu.mx';
const file=id=>{const f=files.get(id);if(!f)throw Error('Archivo inexistente');return {getId:()=>id,getMimeType:()=>f.mime,getSize:()=>Buffer.byteLength(f.text),getLastUpdated:()=>new Date('2026-09-17T00:00:00Z'),getBlob:()=>({getDataAsString:()=>f.text.toString(),getBytes:()=>[...Buffer.from(f.text)]})};};
const context={console:{log(){},error(){}},Session:{getActiveUser:()=>({getEmail:()=>email})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k)||null,setProperty:(k,v)=>properties.set(k,v)})},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},Utilities:{getUuid:()=>crypto.randomUUID(),base64Decode:s=>[...Buffer.from(s,'base64')],base64Encode:b=>Buffer.from(b).toString('base64'),newBlob:(bytes,mime)=>({bytes,mime})},DriveApp:{getFileById:file,getFolderById:()=>({createFile:(name,text,mime)=>{const id=crypto.randomUUID();files.set(id,typeof name==='object'?{text:Buffer.from(name.bytes),mime:name.mime}:{text,mime});return file(id);}})},SpreadsheetApp:{openById:()=>({getSheetByName:name=>({getDataRange:()=>({getDisplayValues:()=>{const keys=Object.keys(data[name][0]);return [keys,...data[name].map(r=>keys.map(k=>r[k]||''))];}})})})},ContentService:{MimeType:{JSON:'json',JAVASCRIPT:'js'},createTextOutput:text=>({text,setMimeType(){return this;}})}};
vm.createContext(context);for(const name of ['Config.gs','Catalogos.gs','Administracion.gs','Servicio.gs'])vm.runInContext(fs.readFileSync(path.join(root,name),'utf8'),context,{filename:name});
vm.runInContext("Object.values(CONFIG_DIN.horarios).forEach(c=>DriveApp.getFolderById('test'));",context);
const config=vm.runInContext('CONFIG_DIN',context);Object.values(config.horarios).forEach(c=>files.set(c.id,{mime:'application/pdf',text:'%PDF-test'}));
let count=0,state;
function test(name,fn){fn();count++;console.log('PASS '+name);}
test('El borrador inicial pasa validación',()=>{const result=context.adminAction({action:'read'});state=result.state;assert.equal(result.errors.length,0);});
test('Rechaza acceso anónimo y otra cuenta',()=>{for(const e of ['', 'other@example.org']){email=e;assert.throws(()=>context.adminAction({action:'read'}),/Acceso denegado/);assert.throws(()=>context.adminAction({action:'publish'}),/Acceso denegado/);}email='ivan.gutierrez@uteq.edu.mx';});
test('Rechaza identificadores duplicados',()=>{assert.throws(()=>context.adminAction({action:'import',revision:state.revision,table:'GRUPOS',period:'2026-3',rows:[data.GRUPOS[0],data.GRUPOS[0]]}),/duplicado/);});
test('Rechaza callback ejecutable',()=>{assert.match(context.doGet({parameter:{action:'manifest',callback:'alert(1)'}}).text,/Callback inválido/);});
test('Publica el conjunto con una revisión',()=>{state=context.adminAction({action:'publish',revision:state.revision}).state;assert.equal(JSON.parse(context.doGet({parameter:{action:'manifest'}}).text).revision,state.revision);});
test('Rechaza escrituras concurrentes antiguas',()=>{assert.throws(()=>context.adminAction({action:'active',revision:'initial',period:'2026-3'}),/Otra sesión/);});
test('No mezcla lecturas de revisiones distintas',()=>{assert.equal(JSON.parse(context.doGet({parameter:{action:'data',sheet:'GRUPOS',revision:'outdated'}}).text).ok,false);});
test('Borrador nuevo no cambia publicación actual',()=>{const revision=state.revision;state=context.adminAction({action:'period',revision,id:'2027-1',name:'Siguiente periodo'}).state;assert.equal(JSON.parse(context.doGet({parameter:{action:'manifest'}}).text).revision,revision);});
test('Impide publicar periodo incompleto',()=>{assert.throws(()=>context.adminAction({action:'publish',revision:state.revision}),/grupos activos/);});
test('Importar un periodo conserva el anterior',()=>{state=context.adminAction({action:'import',revision:state.revision,table:'GRUPOS',period:'2027-1',rows:[{id_grupo:'G2',grupo:'TEST002',periodo:'2027-1',tutor:''}]}).state;assert.equal(state.data.GRUPOS.length,2);});
test('Rechaza geometría fuera del plano',()=>{assert.throws(()=>context.validatePlan_({id:'p',edificio:'e',planta:'ALTA',width:100,height:100,spaces:[{key:'1',x:90,y:0,w:20,h:10}]}),/fuera/);});
test('Rechaza imágenes ejecutables',()=>{assert.throws(()=>context.validatePlan_({id:'p',edificio:'e',planta:'ALTA',width:100,height:100,spaces:[],background:'javascript:alert(1)'}),/Imagen/);});
test('Conserva los 12 planos originales y ubicación por ID',()=>{const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'planos.js'),'utf8'),ctx);assert.equal(ctx.window.DIN_PLANOS.length,12);const model=DIN.model(data,'2026-3',ctx.window.DIN_PLANOS);assert.equal(model.placements(model.groups[0])[0].room.id_aula,'F-ALTA-1');assert.equal(model.geometry(model.rooms[0]).space.key,'1');});
test('Sintaxis de las dos páginas administrativas',()=>{for(const name of ['admin.html','AdminPanel.html'])for(const m of fs.readFileSync(path.join(root,name),'utf8').matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);});
test('Servicio referencia el HTML protegido correcto',()=>{assert.ok(fs.readFileSync(path.join(root,'Servicio.gs'),'utf8').includes("createHtmlOutputFromFile('AdminPanel')"));});
console.log(count+' pruebas correctas');

