/* node tests/schedule-network.cjs — sin acceder a la red */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../horarios.js'),'utf8').replace('return {mount,select:','return {rpc,mount,select:');
function setup(responses){let calls=0;const context={URL,AbortController,TypeError,console,DIN:{norm:s=>s,esc:s=>s},setTimeout:(fn,ms)=>{if(ms<=2000)queueMicrotask(fn);return 1;},clearTimeout(){},fetch:async(url,options)=>{assert.equal(options.credentials,'omit');assert.equal(options.mode,'cors');assert.equal(options.redirect,'follow');assert.equal(new URL(url).searchParams.has('callback'),false);const response=responses[calls++];if(response==='offline')throw new TypeError('Network failure');return {ok:true,json:async()=>response};}};context.window={DIN_CONFIG:{endpoint:'https://script.google.com/macros/s/test/exec'},addEventListener(){}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../remote.js'),'utf8'),context);vm.runInNewContext(source,context);return {rpc:context.window.DIN_SCHEDULE.rpc,calls:()=>calls};}
(async()=>{
 let test=setup(['offline',{ok:true,period:'2026-3'}]);assert.equal((await test.rpc('meta','profesores')).period,'2026-3');assert.equal(test.calls(),2);console.log('PASS recupera una conexión interrumpida');
 test=setup(['offline','offline','offline']);await assert.rejects(test.rpc('meta','profesores'),/servicio público/);assert.equal(test.calls(),3);console.log('PASS limita los reintentos y conserva error visible');
 test=setup([{ok:false,error:'El horario cambió durante la consulta.'}]);await assert.rejects(test.rpc('pdf','grupos','old'),/cambió/);assert.equal(test.calls(),1);console.log('PASS no reintenta respuestas inválidas ni ignora versiones');
 test=setup([{ok:true,period:'2026-3'},{ok:true,period:'2027-1'}]);const first=test.rpc('meta','profesores'),second=test.rpc('meta','profesores');assert.equal(first,second);await first;assert.equal(test.calls(),1);assert.equal((await test.rpc('meta','profesores')).period,'2027-1');console.log('PASS comparte solicitudes simultáneas y vuelve a verificar después');
})().catch(error=>{console.error(error);process.exitCode=1;});
