const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const DIN=require('../datos.js');
for(const value of ['',null,'Sin tutor','SIN TUTORA','FUSIÓN','Pendiente de asignación','—'])assert.equal(DIN.hasTutor(value),false);
assert.equal(DIN.hasTutor('María Guadalupe Lugo Guzmán'),true);
console.log('PASS distingue tutores reales de valores pendientes');
const properties=new Map();let held=false,month="2026-09";
const ctx={Utilities:{formatDate:()=>month},PropertiesService:{getScriptProperties:()=>({getProperty:key=>properties.get(key),setProperty:(key,value)=>{assert.ok(held);properties.set(key,value);}})},LockService:{getScriptLock:()=>({waitLock(){held=true;},releaseLock(){held=false;}})}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../Servicio.gs'),'utf8'),ctx);
assert.equal(ctx.visits_(false).count,0);assert.equal(properties.size,0);
const first=ctx.visits_(true);assert.equal(first.count,1);assert.equal(ctx.visits_(false).count,1);assert.equal(ctx.visits_(true).count,2);assert.equal(ctx.visits_(false).since,first.since);assert.equal(held,false);
assert.deepEqual(Object.keys(JSON.parse(properties.get('DIN_VISITS'))).sort(),['count','month','monthCount','monthSince','since']);
console.log('PASS contador persistente, lectura sin incremento y sin identificadores personales');
assert.equal(ctx.visits_(false).monthCount,2);
month='2026-10';assert.equal(ctx.visits_(false).monthCount,0);assert.equal(ctx.visits_(false).count,2);
const next=ctx.visits_(true);assert.equal(next.count,3);assert.equal(next.monthCount,1);assert.equal(next.month,'2026-10');assert.equal(next.since,first.since);
properties.set('DIN_VISITS',JSON.stringify({count:45,since:first.since}));assert.equal(ctx.visits_(true).count,46);assert.equal(ctx.visits_(false).monthCount,1);
assert.equal(DIN.displayBuildingName('NANO (H1)'),'Nano');assert.equal(DIN.displayBuildingName('Laboratorio D'),'7EE');assert.deepEqual(['Aula 10','Aula 2'].sort(DIN.naturalOrder),['Aula 2','Aula 10']);
console.log('PASS cambio de mes, migración del total y nombres con orden natural');
properties.set('DIN_VISITS','{"count":-1}');assert.throws(()=>ctx.visits_(true),/no disponible/);assert.equal(held,false);
console.log('PASS no reinicia un contador inválido y libera el bloqueo');
